apps/room_book_web/lib/room_book_web/router.ex
defmodule RoomBookWeb.Router do
  use RoomBookWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(RoomBookWeb.Plugs.SetCurrentUser)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", RoomBookWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", PageController, :index)

    resources("/room", RoomController)

    resources("/session", SessionController, only: [:new, :create])

    delete("/sign_out", SessionController, :delete)

    resources("/registration", RegistrationController, only: [:new, :create])
  end

  # Other scopes may use custom stacks.
  # scope "/api", RoomBookWeb do
  #   pipe_through :api
  # end
end

apps/room_book_web/lib/room_book_web/controllers/page_controller.ex
defmodule RoomBookWeb.PageController do
  use RoomBookWeb, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

apps/room_book_web/lib/room_book_web/controllers/registration_controller.ex
defmodule RoomBookWeb.RegistrationController do
  use RoomBookWeb, :controller
  alias RoomBookWeb.Auth

  def new(conn, _params) do
    render(conn, "new.html", changeset: conn)
  end

  def create(conn, %{"registration" => registration_params}) do
    case Auth.register(registration_params) do
      {:ok, user} ->
        conn
        |> put_session(:current_user_id, user.id)
        |> put_flash(:info, "You have successfully signed up!")
        |> redirect(to: room_path(conn, :index))

      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end
end

apps/room_book_web/lib/room_book_web/controllers/room_controller.ex
defmodule RoomBookWeb.RoomController do
  use RoomBookWeb, :controller
  alias RoomBook.{RoomQueries, Room}

  plug RoomBookWeb.Plugs.AuthenticateUser when action not in [:index]

  plug :authorize_user when action in [:edit, :update, :delete]

  def index(conn, _params) do
    rooms = RoomQueries.get_all()
    render(conn, "index.html", rooms: rooms)
  end

  def new(conn, _params) do
    changeset = RoomQueries.change_room(%Room{})
    render(conn, "new.html", changeset: changeset)
  end

  def show(conn, %{"id" => id}) do
    room = RoomQueries.get_by_id(id)
    render(conn, "show.html", room: room)
  end

  def create(conn, %{"room" => room_params}) do
    case RoomQueries.create_room(conn.assigns.current_user,room_params) do
      {:ok, _room} ->
        conn
        |> put_flash(:info, "Room created successfully.")
        |> redirect(to: room_path(conn, :index))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def edit(conn, %{"id" => id}) do
    room = RoomQueries.get_by_id(id)
    changeset = RoomQueries.change_room(room)
    render(conn, "edit.html", room: room, changeset: changeset)
  end

  def update(conn, %{"id" => id, "room" => room_params}) do
    room = RoomQueries.get_by_id(id)

    case RoomQueries.update_room(room, room_params) do
      {:ok, room} ->
        conn
        |> put_flash(:info, "Room updated successfully.")
        |> redirect(to: room_path(conn, :show, room))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", room: room, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    room = RoomQueries.get_by_id(id)

    case RoomQueries.delete_room(room) do
      {:ok, _room} ->
        conn
        |> put_flash(:info, "Room deleted successfully.")
        |> redirect(to: room_path(conn, :index))
    end
  end

  defp authorize_user(conn, _params) do
    %{params: %{"id" => room_id}} = conn
    room = RoomQueries.get_by_id(room_id)
    if RoomBookWeb.Auth.can_manage?(conn.assigns.current_user, room) do
      conn
    else
      conn
      |> put_flash(:error, "You are not authorized to access that page")
      |> redirect(to: room_path(conn, :index))
      |> halt()
    end
  end
end

apps/room_book_web/lib/room_book_web/controllers/session_controller.ex
defmodule RoomBookWeb.SessionController do
  use RoomBookWeb, :controller
  alias RoomBookWeb.Auth

  def new(conn, _params) do
    render(conn, "new.html")
  end

  def create(conn, %{"session" => %{"email" => email, "password" => password}}) do
    case Auth.sign_in(email, password) do
      {:ok, user} ->
        conn
        |> put_session(:current_user_id, user.id)
        |> put_flash(:info, "You have successfully signed in!")
        |> redirect(to: room_path(conn, :index))

      {:error, _reason} ->
        conn
        |> put_flash(:error, "Invalid Email or Password")
        |> render("new.html")
    end
  end

  def delete(conn, _params) do
    conn
    |> Auth.sign_out()
    |> redirect(to: room_path(conn, :index))
  end
end

apps/room_book_web/lib/room_book_web/views/error_view.ex
defmodule RoomBookWeb.ErrorView do
  use RoomBookWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

apps/room_book_web/lib/room_book_web/views/layout_view.ex
defmodule RoomBookWeb.LayoutView do
  use RoomBookWeb, :view
end

apps/room_book_web/lib/room_book_web/views/page_view.ex
defmodule RoomBookWeb.PageView do
  use RoomBookWeb, :view
end

apps/room_book_web/lib/room_book_web/views/registration_view.ex
defmodule RoomBookWeb.RegistrationView do
  use RoomBookWeb, :view

end

apps/room_book_web/lib/room_book_web/views/room_view.ex
defmodule RoomBookWeb.RoomView do
  use RoomBookWeb, :view

end

apps/room_book_web/lib/room_book_web/views/session_view.ex
defmodule RoomBookWeb.SessionView do
  use RoomBookWeb, :view
end

apps/room_book_web/lib/room_book_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello RoomBookWeb!</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
            <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
              <h5 class="my-0 mr-md-auto font-weight-normal">
                <a href="/room" class="navbar-brand text-dark"><strong>RoomBook</strong></a>
              </h5>
               <%= if @user_signed_in? do %>
                  <nav class="my-2 my-md-0 mr-md-3">
                    Hello : <strong><%= @current_user.username %></strong>
                  </nav>
                   <%= link "Sign Out", to: session_path(@conn, :delete), method: :delete, class: "btn btn-outline-primary" %>
               <%= else %>
                  <nav class="my-2 my-md-0 mr-md-3">
                    Hello : <strong>Visitor</strong>
                  </nav>
                   <%= link "Sign In", to: "/session/new", class: "btn btn-outline-primary" %>

                  <nav class="my-2 my-md-0 mr-md-3">
                  
                  </nav>
                    <%= link "Sign Up", to: "/registration/new", class: "btn btn-outline-primary" %>
               <% end %>
      </div>
      </header>
      
      <%= unless is_nil(get_flash(@conn, :info)) do %>
        <p class="alert alert-success" role="alert"><%= get_flash(@conn, :info) %></p>
      <% end %>
      <%= unless is_nil(get_flash(@conn, :error)) do %>
        <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <% end %>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

apps/room_book_web/lib/room_book_web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}", name: "RoomBook List" %></h2>
</div>

apps/room_book_web/lib/room_book_web/templates/room/edit.html.eex
<h2>Edit room: <%= @room.name %></h2>
<%= render "form.html", Map.put(assigns, :action, room_path(@conn, :update, @room)) %>

apps/room_book_web/lib/room_book_web/templates/room/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :description, class: "control-label" %>
    <%= textarea f, :description, class: "form-control", rows: 5 %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

apps/room_book_web/lib/room_book_web/templates/room/index.html.eex
<div class="row">
  <div class="col-md-3">
    <h3>Rooms <%= link "+", to: "/room/new", class: "btn btn-success" %></h3>
    <ul class="list-group">
     <%= for room <- @rooms do %>
      <li class="list-group-item">
        <%= link room.name, to: room_path(@conn, :edit, room.id) %>
        <%= if !is_nil(room.description) && room.description != "" do %>
          <div class="float-right text-info" data-toggle="tooltip" data-placement="right" data-html="true" title="<%= room.description %>">
               <%= if @user_signed_in? do %>
                  <%= link "Delete", to: room_path(@conn, :delete, room.id), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger"%>
                <% end %>
          </div>
        <% end %>
      </li>
     <% end %>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="jumbotron">
      <div class="page-header">
        <h2>Welcome to RoomBook </h2>
      </div>
      <div class="page-header">
        <h2><small>Choose the room on the left to join</small></h2>
        <h2><small>or <%= link "Create", to: "/room/new", class: "btn btn-success" %> a new one</small></h2>
        
      </div>
    </div>
  </div>
</div>

apps/room_book_web/lib/room_book_web/templates/room/new.html.eex
<h2>Add new room</h2>
<%= render "form.html", Map.put(assigns, :action, room_path(@conn, :create)) %>

apps/room_book_web/lib/room_book_web/templates/room/show.html.eex
<h2><%= @room.name %></h2>
<div><%= @room.description %></div>
<br/>
<%= if RoomBookWeb.Auth.can_manage?(@current_user, @room) do %>
  <div>
    <%= link "Edit", to: room_path(@conn, :edit, @room.id), class: "btn btn-default" %>
    <%= link "Delete", to: room_path(@conn, :delete, @room), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger" %>
  </div>
<% end %>

apps/room_book_web/lib/room_book_web/templates/session/new.html.eex
<div class="auth-form-wrapper">
  <%= form_for @conn, session_path(@conn, :create), [as: :session, class: "form-signin"], fn f -> %>
    <div class="text-center mb-4">
      <h1 class="h3 mb-3 font-weight-normal">Sign In</h1>
    </div>

    <div class="form-label-group">
      <%= text_input f, :email, class: "form-control", placeholder: "Email address", required: true, autofocus: true %>
      <%= label f, :email, "Email address", class: "control-label" %>
    </div>

    <div class="form-label-group">
      <%= password_input f, :password, class: "form-control", placeholder: "Password", required: true %>
      <%= label f, :password, class: "control-label" %>
    </div>

    <%= submit "Sign in", class: "btn btn-lg btn-primary btn-block" %>
  <% end %>
</div>